name: Push Base Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Base Images
        run: |
          docker pull golang:1.21-alpine
          docker pull alpine:latest

      - name: Tag and Push Images to GHCR
        run: |
          docker tag golang:1.21-alpine ghcr.io/recursivebugs/hackedvault/golang:1.21-alpine
          docker push ghcr.io/recursivebugs/hackedvault/golang:1.21-alpine
          
          docker tag alpine:latest ghcr.io/recursivebugs/hackedvault/alpine:latest
          docker push ghcr.io/recursivebugs/hackedvault/alpine:latest
